slug: camarafund
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
landscapeMemberCategory: Members
landscapefile: landscape.yml
